<?php
define('WPLDK_DIR', dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'lib'.DIRECTORY_SEPARATOR.'wpldk.'.DIRECTORY_SEPARATOR.'src');

require_once WPLDK_DIR.DIRECTORY_SEPARATOR.'Database'.DIRECTORY_SEPARATOR.'QueryBuilder.php';